# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-yaml
        files: \.(yaml|yml)$
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: requirements-txt-fixer
      # - id: trailing-whitespace
      # - id: check-json
      # - id: end-of-file-fixer
      # - id: flake8
      # - id: pretty-format-json
  - repo: https://github.com/prettier/prettier
    rev: e8037ff25009609ca741ce68f944c97d5fe23968
    hooks:
      - id: prettier
